<a href="https://colab.research.google.com/github/Sarath-I/Array-Operations-using-NumPy/blob/main/Array_Operations_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Array Operations using NumPy**

## **1. Import numpy as np and see the version (Score 1)**

In [ ]:
import numpy as np
print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


## **2. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. (Score:1)**

In [ ]:
arr = np.arange(1, 11)
reshaped_arr = arr.reshape(2, 5)

print("Array:", arr)
print("\nReshaped Matrix:\n", reshaped_arr)

Array: [ 1  2  3  4  5  6  7  8  9 10]

Reshaped Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## **3. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. (Score :2)**

In [ ]:
arr = np.arange(1, 21)
extract_elements = arr[5:16]

print("Array", arr)
print("\nElements between 5th and 15th index:", extract_elements)

Array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Elements between 5th and 15th index: [ 6  7  8  9 10 11 12 13 14 15 16]


## **4. How to compute the mean, median, standard deviation of a numpy array? Use the array you created above (Score 3)**

In [ ]:
mean = np.mean(arr)
median = np.median(arr)
std_deviation = np.std(arr)

print("Array:", arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_deviation)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


### **5. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting. (Score : 2) Note : Score 1 for timely submission.**

In [ ]:
x = np.array([[5, 10, 15, 20],
              [25, 30, 35, 40],
              [45, 50, 55, 60]])

y = np.array([1, 2, 3, 4])

result = x - y

print("x (2D Array):\n", x)
print("\n y (1D Array):", y)
print("\nResult (x - y):\n", result)

x (2D Array):
 [[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]

 y (1D Array): [1 2 3 4]

Result (x - y):
 [[ 4  8 12 16]
 [24 28 32 36]
 [44 48 52 56]]
